
create table board_free_table (
                                   b_no varchar2(20 char) unique,
                                   b_id varchar2(20 char),
                                   b_name varchar2(20 char) not null,
                                   b_begin varchar2(40 char) not null,
                                   b_title varchar2(200 char) not null,
                                   b_img varchar2(200 char) not null,
                                   b_text varchar2(4000 char) not null,
                                   b_date date not null,
                                   FOREIGN KEY (b_id) REFERENCES account_table_hdh(id) ON DELETE CASCADE,
                                   FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname) ON DELETE CASCADE
);
ALTER TABLE board_free_table
    DROP PRIMARY KEY;


create sequence board_free_table_seq;

SELECT MAX(b_no) FROM board_free_table;

DROP SEQUENCE board_free_table_seq;


insert into board_free_table values (board_table_test_seq.nextval,'dul', '호잇이계속되면', '가입인사','안녕하세요' ,'c.jpg','코난이 참 좋아요', sysdate);

select * from board_free_table;

drop table board_free_table;


CREATE TABLE board_free_comment (
                                     c_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 댓글 고유 번호
                                     b_no VARCHAR2(10) NOT NULL,      -- 댓글이 속한 게시글 번호
                                     c_writer VARCHAR2(100) NOT NULL,                       -- 댓글 작성자
                                     c_content CLOB NOT NULL,                                -- 댓글 내용 (TEXT 대신 CLOB 사용)
                                     c_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,             -- 댓글 작성 시간
                                     FOREIGN KEY (b_no) REFERENCES board_free_table(b_no) ON DELETE CASCADE,
                                     FOREIGN KEY (c_writer) REFERENCES ACCOUNT_TABLE_HDH(NICKNAME) ON DELETE CASCADE
);

create sequence board_free_comment_seq;

insert into board_free_comment (b_no, c_writer, c_content, c_date)values (223,'호잇이계속되면', '좋은글입니다.', systimestamp);
select * from board_free_comment;

drop table board_free_comment;
--/////////////////////////////////////////////////////////////////////////////////////

create table board_movie_table (
                                  b_no varchar2(20 char) unique,
                                  b_id varchar2(20 char),
                                  b_name varchar2(20 char) not null,
                                  b_begin varchar2(40 char) not null,
                                  b_title varchar2(200 char) not null,
                                  b_img varchar2(200 char) not null,
                                  b_text varchar2(4000 char) not null,
                                  b_date date not null,
FOREIGN KEY (b_id) REFERENCES account_table_hdh(id) ON DELETE CASCADE,
    FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname) ON DELETE CASCADE
                               );


create sequence board_movie_table_seq;

insert into board_movie_table values (board_table_test_seq.nextval,'dul', '호잇이계속되면', '가입인사','안녕하세요', 'a.jpg' ,'코난이 참 좋아요', sysdate);

select * from board_movie_table;

drop table board_movie_table;


CREATE TABLE board_movie_comment (
                                    c_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 댓글 고유 번호
                                    b_no VARCHAR2(10) NOT NULL,      -- 댓글이 속한 게시글 번호
                                    c_writer VARCHAR2(100) NOT NULL,                        -- 댓글 작성자
                                    c_content CLOB NOT NULL,                                -- 댓글 내용 (TEXT 대신 CLOB 사용)
                                    c_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,             -- 댓글 작성 시간
                                    FOREIGN KEY (b_no) REFERENCES board_movie_table(b_no) ON DELETE CASCADE,
                                    FOREIGN KEY (c_writer) REFERENCES ACCOUNT_TABLE_HDH(NICKNAME) ON DELETE CASCADE
);

create sequence board_movie_comment_seq;

insert into board_movie_comment (b_no, c_writer, c_content, c_date)values (224, '호잇이계속되면', '좋은글입니다.', systimestamp);
select * from board_movie_comment;

drop table board_movie_comment;
--/////////////////////////////////////////////////////////////////////////////////////
--/////////////////////////////////////////////////////////////////////////////////////

create table board_notice_table (
                                   b_no varchar2(20 char) unique,
                                   b_id varchar2(20 char),
                                   b_name varchar2(20 char) not null,
                                   b_begin varchar2(40 char) not null,
                                   b_title varchar2(200 char) not null,
                                   b_img varchar2(200 char) not null,
                                   b_text varchar2(4000 char) not null,
                                   b_date date not null,
                                   FOREIGN KEY (b_id) REFERENCES account_table_hdh(id) ON DELETE CASCADE,
                                   FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname) ON DELETE CASCADE
);


create sequence board_notice_table_seq;

insert into board_notice_table values (board_table_test_seq.nextval,'dul', '호잇이계속되면', '가입인사','안녕하세요','b.jpg','코난이 참 좋아요', sysdate);

select * from board_notice_table;

drop table board_notice_table;


CREATE TABLE board_notice_comment (
                                     c_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 댓글 고유 번호
                                     b_no VARCHAR2(10) NOT NULL,      -- 댓글이 속한 게시글 번호
                                    c_writer VARCHAR2(100) NOT NULL,                        -- 댓글 작성자
                                     c_content CLOB NOT NULL,                                -- 댓글 내용 (TEXT 대신 CLOB 사용)
                                     c_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,             -- 댓글 작성 시간
                                     FOREIGN KEY (b_no) REFERENCES board_notice_table(b_no) ON DELETE CASCADE,
                                     FOREIGN KEY (c_writer) REFERENCES ACCOUNT_TABLE_HDH(NICKNAME) ON DELETE CASCADE
);

create sequence board_notice_comment_seq;

insert into board_notice_comment (b_no, c_writer, c_content, c_date)values (225, '호잇이계속되면', '좋은글입니다.', systimestamp);
select * from board_notice_comment;

drop table board_notice_comment;
--/////////////////////////////////////////////////////////////////////////////////////

create table board_anime_table (
                                   b_no varchar2(20 char) unique,
                                   b_id varchar2(20 char),
                                   b_name varchar2(20 char) not null,
                                   b_begin varchar2(40 char) not null,
                                   b_title varchar2(200 char) not null,
                                   b_img varchar2(200 char) not null,
                                   b_text varchar2(4000 char) not null,
                                   b_date date not null,
                                   FOREIGN KEY (b_id) REFERENCES account_table_hdh(id) ON DELETE CASCADE,
                                   FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname) ON DELETE CASCADE
);


create sequence board_anime_table_seq;

insert into board_anime_table values (board_table_test_seq.nextval,'dul', '호잇이계속되면', '가입인사','안녕하세요','c.jpg','코난이 참 좋아요', sysdate);

select * from board_anime_table;

drop table board_anime_table;


CREATE TABLE board_anime_comment (
                                     c_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 댓글 고유 번호
                                     b_no VARCHAR2(10) NOT NULL,      -- 댓글이 속한 게시글 번호
                                     c_writer VARCHAR2(100) NOT NULL,                        -- 댓글 작성자
                                     c_content CLOB NOT NULL,                                -- 댓글 내용 (TEXT 대신 CLOB 사용)
                                     c_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,             -- 댓글 작성 시간
                                     FOREIGN KEY (b_no) REFERENCES board_anime_table(b_no) ON DELETE CASCADE,
                                     FOREIGN KEY (c_writer) REFERENCES ACCOUNT_TABLE_HDH(NICKNAME) ON DELETE CASCADE
);

create sequence board_anime_comment_seq;

insert into board_anime_comment (b_no, c_writer, c_content, c_date)values (226,'호잇이계속되면', '좋은글입니다.', systimestamp);
select * from board_anime_comment;

drop table board_anime_comment;