create table board_free_table (
    b_no varchar2(20 char) unique,
    b_id varchar2(20 char),
    b_name varchar2(20 char) not null,
    b_begin varchar2(40 char) not null,
    b_title varchar2(200 char) not null,
    b_img varchar2(200 char) not null,
    b_text varchar2(4000 char) not null,
    b_date date not null,
    FOREIGN KEY (b_id) REFERENCES account_table_hdh(id) ON DELETE CASCADE,
    FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname) ON DELETE CASCADE
);
ALTER TABLE board_free_table
    DROP PRIMARY KEY;



create sequence board_free_table_seq;

SELECT MAX(b_no) FROM board_free_table;

DROP SEQUENCE board_free_table_seq;


insert into board_free_table values (board_table_test_seq.nextval,'dul', '호잇이계속되면', '가입인사','안녕하세요' ,'c.jpg','코난이 참 좋아요', sysdate);

select * from board_free_table;

drop table board_free_table;


CREATE TABLE board_free_comment (
    c_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 댓글 고유 번호
    b_no VARCHAR2(10) NOT NULL,      -- 댓글이 속한 게시글 번호
    c_writer VARCHAR2(100) NOT NULL,                       -- 댓글 작성자
    c_content CLOB NOT NULL,                                -- 댓글 내용 (TEXT 대신 CLOB 사용)
    c_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,             -- 댓글 작성 시간
    FOREIGN KEY (b_no) REFERENCES board_free_table(b_no) ON DELETE CASCADE,
    FOREIGN KEY (c_writer) REFERENCES ACCOUNT_TABLE_HDH(NICKNAME) ON DELETE CASCADE
);

create sequence board_free_comment_seq;

insert into board_free_comment (b_no, c_writer, c_content, c_date)values (223,'호잇이계속되면', '좋은글입니다.', systimestamp);
select * from board_free_comment;

drop table board_free_comment;
--/////////////////////////////////////////////////////////////////////////////////////

create table board_movie_table (
    b_no varchar2(20 char) unique,
    b_id varchar2(20 char),
    b_name varchar2(20 char) not null,
    b_begin varchar2(40 char) not null,
    b_title varchar2(200 char) not null,
    b_img varchar2(200 char) not null,
    b_text varchar2(4000 char) not null,
    b_date date not null,
FOREIGN KEY (b_id) REFERENCES account_table_hdh(id) ON DELETE CASCADE,

    FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname) ON DELETE CASCADE
    );


create sequence board_movie_table_seq;

insert into board_movie_table values (board_table_test_seq.nextval,'dul', '호잇이계속되면', '가입인사','안녕하세요', 'a.jpg' ,'코난이 참 좋아요', sysdate);

select * from board_movie_table;

drop table board_movie_table;


CREATE TABLE board_movie_comment (
    c_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 댓글 고유 번호
    b_no VARCHAR2(10) NOT NULL,      -- 댓글이 속한 게시글 번호
    c_writer VARCHAR2(100) NOT NULL,                        -- 댓글 작성자
    c_content CLOB NOT NULL,                                -- 댓글 내용 (TEXT 대신 CLOB 사용)
    c_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,             -- 댓글 작성 시간
    FOREIGN KEY (b_no) REFERENCES board_movie_table(b_no) ON DELETE CASCADE,
    FOREIGN KEY (c_writer) REFERENCES ACCOUNT_TABLE_HDH(NICKNAME) ON DELETE CASCADE
);

create sequence board_movie_comment_seq;

insert into board_movie_comment (b_no, c_writer, c_content, c_date)values (224, '호잇이계속되면', '좋은글입니다.', systimestamp);
select * from board_movie_comment;

drop table board_movie_comment;
--/////////////////////////////////////////////////////////////////////////////////////
--/////////////////////////////////////////////////////////////////////////////////////

create table board_notice_table (

    b_no varchar2(20 char) unique,
    b_id varchar2(20 char),
    b_name varchar2(20 char) not null,
    b_begin varchar2(40 char) not null,
    b_title varchar2(200 char) not null,
    b_img varchar2(200 char) not null,
    b_text varchar2(4000 char) not null,
    b_date date not null,
    FOREIGN KEY (b_id) REFERENCES account_table_hdh(id) ON DELETE CASCADE,
    FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname) ON DELETE CASCADE

);


create sequence board_notice_table_seq;

insert into board_notice_table values (board_table_test_seq.nextval,'dul', '호잇이계속되면', '가입인사','안녕하세요','b.jpg','코난이 참 좋아요', sysdate);

select * from board_notice_table order by b_date desc ;

drop table board_notice_table;


CREATE TABLE board_notice_comment (
    c_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 댓글 고유 번호
    b_no VARCHAR2(10) NOT NULL,      -- 댓글이 속한 게시글 번호
    c_writer VARCHAR2(100) NOT NULL,                        -- 댓글 작성자
    c_content CLOB NOT NULL,                                -- 댓글 내용 (TEXT 대신 CLOB 사용)
    c_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,             -- 댓글 작성 시간
    FOREIGN KEY (b_no) REFERENCES board_notice_table(b_no) ON DELETE CASCADE,
    FOREIGN KEY (c_writer) REFERENCES ACCOUNT_TABLE_HDH(NICKNAME) ON DELETE CASCADE
);

create sequence board_notice_comment_seq;

insert into board_notice_comment (b_no, c_writer, c_content, c_date)values (225, '호잇이계속되면', '좋은글입니다.', systimestamp);
select * from board_notice_comment;

drop table board_notice_comment;
--/////////////////////////////////////////////////////////////////////////////////////

create table board_anime_table (

    b_no varchar2(20 char) unique,
    b_id varchar2(20 char),
    b_name varchar2(20 char) not null,
    b_begin varchar2(40 char) not null,
    b_title varchar2(200 char) not null,
    b_img varchar2(200 char) not null,
    b_text varchar2(4000 char) not null,
    b_date date not null,
    FOREIGN KEY (b_id) REFERENCES account_table_hdh(id) ON DELETE CASCADE,
    FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname) ON DELETE CASCADE

);


create sequence board_anime_table_seq;

insert into board_anime_table values (board_table_test_seq.nextval,'dul', '호잇이계속되면', '가입인사','안녕하세요','c.jpg','코난이 참 좋아요', sysdate);

select * from board_anime_table;

drop table board_anime_table;


CREATE TABLE board_anime_comment (
    c_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 댓글 고유 번호
    b_no VARCHAR2(10) NOT NULL,      -- 댓글이 속한 게시글 번호
    c_writer VARCHAR2(100) NOT NULL,                        -- 댓글 작성자
    c_content CLOB NOT NULL,                                -- 댓글 내용 (TEXT 대신 CLOB 사용)
    c_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,             -- 댓글 작성 시간
    FOREIGN KEY (b_no) REFERENCES board_anime_table(b_no) ON DELETE CASCADE,
    FOREIGN KEY (c_writer) REFERENCES ACCOUNT_TABLE_HDH(NICKNAME) ON DELETE CASCADE
);

create sequence board_anime_comment_seq;

insert into board_anime_comment (b_no, c_writer, c_content, c_date)values (226,'호잇이계속되면', '좋은글입니다.', systimestamp);
select * from board_anime_comment;

drop table board_anime_comment;

-----------------------------------------------------------------
-- -- 1. 외래 키 제약 조건 수정하기
-- -- 현재 자식 테이블에서 부모 테이블을 참조하는 외래 키 제약 조건에 ON UPDATE CASCADE를 추가해야 합니다. 이렇게 하면 부모 테이블의 nickname이나 id 값이 변경될 때, 이를 참조하는 자식 테이블의 관련 값도 자동으로 업데이트됩니다.
--
-- -- 2. 각 자식 테이블에 대해 외래 키 수정
-- -- 자식 테이블들이 부모 테이블의 nickname이나 id를 참조하는 외래 키를 가지고 있을 것입니다. 이를 수정하여 ON UPDATE CASCADE 옵션을 추가해야 합니다.
-- -- 다음은 자식 테이블에 외래 키 제약 조건을 수정하는 SQL입니다:
--
-- -- 2.1. board_free_table의 외래 키 수정
-- -- 기존 외래 키 삭제
-- ALTER TABLE board_free_table
--     DROP CONSTRAINT fk_b_name;
--
-- -- 새로운 외래 키 추가 (ON UPDATE CASCADE 적용)
-- ALTER TABLE board_free_table
--     ADD CONSTRAINT fk_b_name FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname)
--         ON DELETE CASCADE ON UPDATE CASCADE;
--
-- -- 2.2. board_movie_table의 외래 키 수정
-- -- 기존 외래 키 삭제
-- ALTER TABLE board_movie_table
--     DROP CONSTRAINT fk_b_name;
--
-- -- 새로운 외래 키 추가 (ON UPDATE CASCADE 적용)
-- ALTER TABLE board_movie_table
--     ADD CONSTRAINT fk_b_name FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname)
--         ON DELETE CASCADE ON UPDATE CASCADE;
--
-- -- 2.3. board_notice_table의 외래 키 수정
-- -- 기존 외래 키 삭제
-- ALTER TABLE board_notice_table
--     DROP CONSTRAINT fk_b_name;
--
-- -- 새로운 외래 키 추가 (ON UPDATE CASCADE 적용)
-- ALTER TABLE board_notice_table
--     ADD CONSTRAINT fk_b_name FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname)
--         ON DELETE CASCADE ON UPDATE CASCADE;
--
-- -- 2.4. board_anime_table의 외래 키 수정
-- -- 기존 외래 키 삭제
-- ALTER TABLE board_anime_table
--     DROP CONSTRAINT fk_b_name;
--
-- -- 새로운 외래 키 추가 (ON UPDATE CASCADE 적용)
-- ALTER TABLE board_anime_table
--     ADD CONSTRAINT fk_b_name FOREIGN KEY (b_name) REFERENCES account_table_hdh(nickname)
--         ON DELETE CASCADE ON UPDATE CASCADE;
--
-- -- 3. 왜 ON UPDATE CASCADE를 사용해야 하는지
-- -- ON UPDATE CASCADE를 사용하면 부모 테이블(account_table_hdh)의 nickname이나 id가 변경될 때,
-- -- 해당 값을 참조하는 자식 테이블(board_free_table, board_movie_table, board_notice_table, board_anime_table)의 관련 레코드도 자동으로 업데이트됩니다.
-- -- 이를 통해 수동으로 자식 테이블을 업데이트하거나 삭제하는 과정을 생략할 수 있게 됩니다.
--
-- -- 4. 부모 테이블 업데이트
-- -- 이제 부모 테이블의 nickname이나 id를 수정할 때, 자식 테이블의 관련 값도 자동으로 업데이트됩니다.
-- UPDATE account_table_hdh
-- SET name = :name, e_mail = :e_mail, pw = :pw, pw_check = :pw_check, nickname = :nickname
-- WHERE id = :id;
--
-- -- 자식 테이블의 외래 키 제약 조건 이름을 확인하는 쿼리
-- SELECT constraint_name
-- FROM user_constraints
-- WHERE table_name = 'BOARD_FREE_TABLE'  -- 자식 테이블 이름
--   AND constraint_type = 'R';  -- 외래 키 제약 조건(R은 외래 키를 의미)
--
-- ALTER TABLE board_free_table
--     DROP CONSTRAINT FK_B_NAME;  -- 외래 키 제약 조건 이름


---------------------------------------------------
---------------------------------------------------
---------------------------------------------------
---------------------------------------------------
-- [위에꺼 쭉 해봤는데 안 됨,] Oracle은 ON UPDATE CASCADE를 직접 지원하지 않기 때문에, 이를 트리거로 구현해야 합니다.
-- 트리거를 사용하여 부모 테이블의 변경을 자식 테이블에 반영하도록 처리합니다.
-- 이 방법을 통해 nickname 값이 변경되면 자동으로 자식 테이블에서 관련 값도 업데이트됩니다.

-- 트리거 설계:
-- 트리거가 작동하는 시점: 부모 테이블(account_table_hdh)의 nickname이 변경될 때.
-- 트리거가 수행해야 할 작업: 변경된 nickname 값을 자식 테이블의 b_name 컬럼에 반영.

-- board_free_table에 대한 트리거
CREATE OR REPLACE TRIGGER trg_board_free_table_nickname_update
    AFTER UPDATE OF nickname ON account_table_hdh
    FOR EACH ROW
BEGIN
    -- 부모 테이블에서 변경된 nickname 값을 자식 테이블에 반영
    UPDATE board_free_table
    SET b_name = :NEW.nickname  -- 새로운 nickname 값을 b_name에 반영
    WHERE b_name = :OLD.nickname;  -- 기존 nickname 값을 찾아서 업데이트
END;
/

-- board_movie_table에 대한 트리거
CREATE OR REPLACE TRIGGER trg_board_movie_table_nickname_update
    AFTER UPDATE OF nickname ON account_table_hdh
    FOR EACH ROW
BEGIN
    -- 부모 테이블에서 변경된 nickname 값을 자식 테이블에 반영
    UPDATE board_movie_table
    SET b_name = :NEW.nickname  -- 새로운 nickname 값을 b_name에 반영
    WHERE b_name = :OLD.nickname;  -- 기존 nickname 값을 찾아서 업데이트
END;
/

-- board_notice_table에 대한 트리거
CREATE OR REPLACE TRIGGER trg_board_notice_table_nickname_update
    AFTER UPDATE OF nickname ON account_table_hdh
    FOR EACH ROW
BEGIN
    -- 부모 테이블에서 변경된 nickname 값을 자식 테이블에 반영
    UPDATE board_notice_table
    SET b_name = :NEW.nickname  -- 새로운 nickname 값을 b_name에 반영
    WHERE b_name = :OLD.nickname;  -- 기존 nickname 값을 찾아서 업데이트
END;
/

-- board_anime_table에 대한 트리거
CREATE OR REPLACE TRIGGER trg_board_anime_table_nickname_update
    AFTER UPDATE OF nickname ON account_table_hdh
    FOR EACH ROW
BEGIN
    -- 부모 테이블에서 변경된 nickname 값을 자식 테이블에 반영
    UPDATE board_anime_table
    SET b_name = :NEW.nickname  -- 새로운 nickname 값을 b_name에 반영
    WHERE b_name = :OLD.nickname;  -- 기존 nickname 값을 찾아서 업데이트
END;
/

------------선생님이 도와주신 부분(4개의 테이블 트리거 작성은 완료했는데, 알고보니 4개의 코멘트 트리거 작성을 하지 않아서 오류가 떴던거임;;)
CREATE OR REPLACE TRIGGER trg_board_anime_comment_nickname_update
    AFTER UPDATE OF nickname ON account_table_hdh
    FOR EACH ROW
BEGIN
    -- 부모 테이블에서 변경된 nickname 값을 자식 테이블에 반영
    UPDATE board_anime_comment
    SET c_writer = :NEW.nickname  -- 새로운 nickname 값을 b_name에 반영
    WHERE c_writer = :OLD.nickname;  -- 기존 nickname 값을 찾아서 업데이트
END;

CREATE OR REPLACE TRIGGER BOARD_FREE_COMMENT_nickname_update
    AFTER UPDATE OF nickname ON account_table_hdh
    FOR EACH ROW
BEGIN
    -- 부모 테이블에서 변경된 nickname 값을 자식 테이블에 반영
    UPDATE board_free_comment
    SET c_writer = :NEW.nickname  -- 새로운 nickname 값을 b_name에 반영
    WHERE c_writer = :OLD.nickname;  -- 기존 nickname 값을 찾아서 업데이트
END;


CREATE OR REPLACE TRIGGER BOARD_FREE_movie_nickname_update
    AFTER UPDATE OF nickname ON account_table_hdh
    FOR EACH ROW
BEGIN
    -- 부모 테이블에서 변경된 nickname 값을 자식 테이블에 반영
    UPDATE board_movie_comment
    SET c_writer = :NEW.nickname  -- 새로운 nickname 값을 b_name에 반영
    WHERE c_writer = :OLD.nickname;  -- 기존 nickname 값을 찾아서 업데이트
END;


CREATE OR REPLACE TRIGGER BOARD_FREE_notice_nickname_update
    AFTER UPDATE OF nickname ON account_table_hdh
    FOR EACH ROW
BEGIN
    -- 부모 테이블에서 변경된 nickname 값을 자식 테이블에 반영
    UPDATE board_notice_comment
    SET c_writer = :NEW.nickname  -- 새로운 nickname 값을 b_name에 반영
    WHERE c_writer = :OLD.nickname;  -- 기존 nickname 값을 찾아서 업데이트
END;
--------------------------------------------------------------------
