CREATE TABLE characters_test_nr (
    id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    name          VARCHAR2(100 CHAR) NOT NULL,
    age           VARCHAR2(10 CHAR),    -- 나이 대신 “불명”, “10/15” 등 어떤 문자열이든 가능
    quote         CLOB,
    description   CLOB,
    button_image  VARCHAR2(255 CHAR),
    main_image    VARCHAR2(255 CHAR)
);

select *
from characters_test_nr;

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES
    (
        '에도가와 코난 (코난)',
        '7세',
        '"몸은 작아졌어도, 두뇌는 그대로! 진실은 언제나 하나!"',
        '명탐정 코난의 주인공이며, 남도일이 APTX-4869를 먹고 어린아이가 된 모습이다.'|| CHR(10) ||
        '소꿉친구이자 고등학교 친구인 란과 놀이공원에 갔다가, 검은 옷을 입은 남자의 수상한 거래 현장을 목격하고' || CHR(10) ||
        '억지로 약을 먹어 초등학생이 되어 버린다.',
        'img/Characters/conan/conan.png',
        'img/Characters/conan/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES
    (
        '쿠도 신이치 (남도일)',
        '17세',
        '"저 말인가요?"',
        '명탐정 코난의 주인공 ''에도가와 코난''의 본래 정체.' || CHR(10) ||
        '테이탄 고등학교 2학년 B반으로, 현재는 휴학 중이다.' || CHR(10) ||
        '셜록 홈즈를 동경하는 유명한 고등학생 명탐정이며, 머리·운동신경·외모까지 모두 갖춘 ''엄친아 캐릭터''이다.',
        'img/Characters/shinichi/shinichi.png',
        'img/Characters/shinichi/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES
    (
        '모리 란 (유미란)',
        '16세',
        '"얘, 코난! 어른들 일하는데 방해하면 안 된다고 말했잖아."',
        '명탐정 코난의 메인 히로인으로, 주인공 쿠도 신이치의 소꿉친구이자 ' || CHR(10) ||
        '테이탄 고등학교 2학년 B반이다.가라테에 상당한 실력을 갖추고 있다.' || CHR(10) ||
        '놀이공원에 함께 간 날, 신이치가 갑자기 사라지자 그를 찾으러 아가사 박사를 찾았다가' || CHR(10) ||
        '그 부탁으로 코난을 모리 탐정 사무소로 데려와 함께 살고 있다.',
        'img/Characters/ran/ran.png',
        'img/Characters/ran/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('모리 코고로 (유명한)',
        '38세',
        '"으헹힝힝힝~ 오셨구나 오셨어~! 반장님, 잠깐만 기다려 주십시오."',
        '란의 아버지로, 전 경시청 수사1과 형사 출신이라 메구레 경부와 인연이 있다.' || CHR(10) ||
        '퇴직 후 ''모리 탐정 사무소''를 열었는데, 란이 데려온 코난 덕분에' || CHR(10) ||
        '''잠자는 명탐정''으로 유명해지고 있다.',
        'img/Characters/kogoro/kogoro.png',
        'img/Characters/kogoro/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('아가사 히로시 (브라운)',
        '53세',
        '"자, 기다리던 퀴즈 시간이란다~!"',
        '신이치의 옆집에 사는 발명가로, 코난의 정체를 아는 몇 안 되는 인물 중 한 명이다.' || CHR(10) ||
        '코난이 사용하는 발명품들의 개발자이며, 주로 어린이 탐정단을 돌봐준다.' || CHR(10) ||
        '하이바라 아이가 조직을 탈출한 뒤에는 집에서 함께 지내며 보살펴 주고 있다.',
        'img/Characters/agasa/agasa.png',
        'img/Characters/agasa/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('하이바라 아이 (홍장미)',
        '7세',
        '"운명으로부터 도망치지 말라고 했잖아. 네가 지켜줄 거지?"',
        '명탐정 코난의 서브 히로인. 겉모습은 어린아이지만, 사실 검은 조직의 일원으로' || CHR(10) ||
        'APTX-4869를 개발했던 장본인이며이다. 코드네임은 ''셰리''. 언니가 조직에게 살해당하자 복수를 위해' || CHR(10) ||
        '조직을 배신하고 약을 먹어 초등학생이 되었다.',
        'img/Characters/haibara/haibara.png',
        'img/Characters/haibara/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('요시다 아유미 (한아름)',
        '7세',
        '"도망치기 싫어. 도망쳐서는 이길 수가 없는 걸, 절대로!"',
        '코난과 같은 반 친구이자 어린이 탐정단의 ''아이돌'' 같은 존재.' || CHR(10) ||
        '호기심이 많지만 울보이기도 하다. 순진하고 솔직한 성격으로,' || CHR(10) ||
        '한때 코난을 좋아해 하이바라를 질투하기도 했지만 지금은 친하게 지낸다.',
        'img/Characters/ayumi/ayumi.png',
        'img/Characters/ayumi/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('츠부라야 미츠히코 (박세모)',
        '7세',
        '"아직 아무 일도 일어나지 않았다면, 앞으로도 일어나지 않도록 미리 막으면 되잖아."',
        '코난과 같은 반 친구이자 어린이 탐정단의 일원. 진지하고 예의 바른 두뇌파 캐릭터로,' || CHR(10) ||
        '가끔 독단적으로 행동하기도 하지만 나이에 비해 똑똑해 사건 해결에 도움을 줄 때가 있다.',
        'img/Characters/mitsuhiko/mitsuhiko.png',
        'img/Characters/mitsuhiko/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('코지마 겐타 (고뭉치)',
        '7세',
        '"장어덮밥 몇 개 사 먹을 수 있는데?"',
        '코난과 같은 반 친구이자 어린이 탐정단의 자칭 리더. 대식가이며 힘이 센 먹보로,' || CHR(10) ||
        '장어덮밥을 매우 좋아한다. 정의감이 강한 성격이지만, 자주 사고를 치기도 한다.',
        'img/Characters/genta/genta.png',
        'img/Characters/genta/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('스즈키 소노코 (정보라)',
        '17세',
        '"안경잡이 꼬맹이, 너 또 미란이 쫓아다니는 거니?"',
        '란과 같은 반 친구로, 유치원 때부터 함께한 절친. 신이치와도 같은 반 친구이다.' || CHR(10) ||
        '세계적인 재벌 ''스즈키 가문''의 아가씨이며, 현재 쿄고쿠 마코토와 연애 중이다.',
        '"img/Characters/sonoko/sonoko.png',
        'img/Characters/sonoko/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('핫토리 헤이지 (하인성)',
        '17세',
        '"뭐가 어째?! 그건 내가 할 말이야! 너 이 자식… 우리, 우리 가영이에게 무슨 짓을 한 거야"',
        '신이치의 라이벌이자 절친으로, 오사카에 사는 고등학생 탐정.' || CHR(10) ||
        '''서쪽의 고등학생 명탐정''으로 불리며, 아버지가 오사카부 경찰본부장이다.' || CHR(10) ||
        '코난의 정체를 알고 있는 몇 안 되는 인물로, 종종 함께 사건을 해결한다.',
        'img/Characters/heiji/heiji.png',
        'img/Characters/heiji/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('토야마 카즈하 (서가영)',
        '17세',
        '"실은 있잖아, 나도 말이야… 나도 오래전부터 인성이, 널 정말 좋아했어!!"',
        '헤이지의 소꿉친구이자 여자 친구. 합기도에 능하며, 아버지는 오사카부 경찰본부 형사부장.' || CHR(10) ||
        '솔직하고 배려심 많은 성격으로, 란과도 절친한 사이.' || CHR(10) ||
        '헤이지가 사건 때문에 도쿄에 올라올 때면 늘 동행한다.',
        'img/Characters/kazuha/kazuha.png',
        'img/Characters/kazuha/main_img.png'
    );

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('세라 마스미 (양세라)',
        '17세',
        '"Case Closed!"',
        '란의 반으로 전학 온 여고생 탐정. 처음 본 사람들은 대부분 남자라고 착각할 정도로 보이시한 외모.' || CHR(10) ||
        '아카이 슈이치와 하네다 슈키치의 여동생이며, 뛰어난 추리력을 지니고 있다.' || CHR(10) ||
        '코난과 신이치의 관계를 의심 하고있다.',
        'img/Characters/sera/sera.png',
        'img/Characters/sera/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('오키야 스바루 (최수현)',
        '27세',
        '"카레를 만들었는데 너무 많이 만들어서요. 나눠 드리려고요."',
        '신이치의 저택에 얹혀살고 있는 대학원생. 늘 음식을 많이 만들어 ' || CHR(10) ||
        '이웃인 아가사 박사에게 나누어주곤 한다. 시종일관 여유롭고 침착한 성격으로' || CHR(10) ||
        '등장 초기, 하이바라가 공포를 느꼈으나 사실 그는 위장사 한 아카이 슈이치가 변장한 모습이었다.',
        'img/Characters/subaru/subaru.png',
        'img/Characters/subaru/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('쿄고쿠 마코토 (오경구)',
        '18세',
        '"자 이제 그만 돌려주실까. 그 보석이랑, 그리고 보라의 마음까지 다."',
        '통칭 ''돌려차기의 귀공자''이자 소노코의 연인. ' || CHR(10) ||
        '고등학생이지만, 무술 수련을 위해 해외를 돌아다니고 있다.' || CHR(10) ||
        '하지만 소노코에게 무슨일이 있으면 바로 시합을 내팽개치고 귀국해서 돌아온다.' || CHR(10) ||
        '보수적인 성격으로 보라가 노출있는 의상을 입을때 주의를 준다.',
        'img/Characters/kyogoku/.png',
        'img/Characters/kyogoku/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('쿠도 유사쿠 (남건)',
        '39세',
        '"저는 탐정이 아니에요. 그냥 평범한 소설가일 뿐입니다."',
        '주인공 쿠도 신이치의 아버지이자 세계적으로 유명한 추리소설 작가이다. ' || CHR(10) ||
        '신이치 이상의 두뇌와 추리력을 가진 유일한 인물. 종종 신이치의 추리에 조언을 주기도 한다. ' || CHR(10) ||
        '보기와 다르게 장난을 좋아하는 편이다.',
        'img/Characters/yusaku/yusaku.png',
        'img/Characters/yusaku/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('쿠도 유키코 (이하연)',
        '38세 ',
        '"그리고 어린아이로 돌아간 도일이의 사진.. 잔뜩 찍어서 가져가고 싶었거든~ "',
        '신이치의 어머니이자 옛날에는 인기 여배우였지만 유사쿠와 결혼하면서 동시에 은퇴했다.' || CHR(10) ||
        '천진난만한 성격이며, 남편인 유사쿠와 함께 외국을 돌아다니며 생활중.' || CHR(10) ||
        '변장에 능하며 연기력도 좋아 주변 사람들을 속이는 재주가 있다.',
        'img/Characters/yukiko/yukiko.png',
        'img/Characters/yukiko/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('괴도키드(고희도)',
        '17세',
        '"네, 전 탐정이 아닌 도둑입니다. 도둑은 훔치는 게 일이죠. 설령 그게, 사람의 마음일지라도…"',
        '신이치의 라이벌이자 ''월하의 마술사''라 불리는 신출귀몰의 괴도.' || CHR(10) ||
        '''키드''라는 명칭은 국제 범죄자 번호인 1412를 유사쿠가 휘갈겨 쓴 글자에서 따와서 칭하면서 유명해졌다.' || CHR(10) ||
        '반드시 범죄 전에 예고장을 보내고 경찰들을 완벽히 따돌리는 모습을 보여준다.',
        'img/Characters/kid/kid.png',
        'img/Characters/kid/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('메구레 쥬조 (골롬보 반장, 골한석)',
        '41세',
        '"아니, 또 너였냐? 코난! 사건을 터트리고 다니는 불청객은 유탐정인줄 알았는데 이제보니 코난 너였구나."',
        '경시청 수사 1과 강력3계의 경부. 코고로의 형사시절 상사이기도 하다.' || CHR(10) ||
        '평소 너그럽고 성격이지만, 부하들에겐 엄격한 면도 있어서 존경을 받는 편.' || CHR(10) ||
        '항상 쓰고 다니는 모자는 옛 사건으로 입은 상처를 감추기 위해서이다.',
        'img/Characters/megure/megure.png',
        'img/Characters/megure/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('시라토리 닌자부로 (백동훈)',
        '28세',
        '"만나서 반갑다. 네 얘기는 반장님께 많이 들었단다. 재밌는 발상을 잘하는 아이라면서?"',
        '경시청 수사 1과 강력3계의 캐리어 조 경부.' || CHR(10) ||
        '엘리트 형사로 냉정하고 침착한 성격이며, 약간 고지식한 면이 있다. 주변으로부터 신뢰를 받고 있다. ',
        'img/Characters/shiratori/shiratori.png',
        'img/Characters/shiratori/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('사토 미와코 (오지인)',
        '28세',
        '"사건 이름이나 범인의 이름은 기억에 남아도, 그 사건으로 순직한 경찰관의 이름은 경찰 관계자가 아니면 아무도 기억하지 않아."',
        '경시청 수사 1과 강력3계의 형사. 메구레 경부의 부하이자 우수한 형사로,' || CHR(10) ||
        '실력과 미모를 모두 겸비해 경시청 내에서 인기가 상당하다.' || CHR(10) ||
        '아버지가 순직한 과거 사건에서 벗어나 지금은 타카기 형사와 연인관계이다.',
        'img/Characters/sato/sato.png',
        'img/Characters/sato/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('타카기 와타루 (신형선)',
        '26세',
        '"잊어선.. 안됩니다.. 그게 소중한 추억이라면 더더욱 잊어서는 안 돼요.. 세상을 떠나면 기억해 주는 사람의 추억에서만... 살 수 있으니까요."',
        '경시청 수사 1과 강력3계의 형사.' || CHR(10) ||
        '메구레 경부의 부하이자, 덜렁거리는 성격으로 아이들과도 잘 어울리는 모습을 보여준다.' || CHR(10) ||
        '하지만 때때로 사건의 핵심을 찌르기도 한다. 직장에서 인기 있는 사토형사와 연애중이지만 주변에서 질투와 방해를 받고 있다.',
        'img/Characters/takagi/takagi.png',
        'img/Characters/takagi/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('치바 카즈노부 (이명수)',
        '24세',
        '"한 번 자신에게 관대하여 규칙을 어기면 버릇이 돼. 버릇은 고치려고 해도 못 고친단 말이야. 넌 그런 것도 몰라?"',
        '경시청 수사 1과 강력3계의 형사. 메구레 경부의 부하로 타카기 형사의 후배이다. ' || CHR(10) ||
        '특수촬영물을 좋아한다. 먹는 것을 좋아하는 편.',
        'img/Characters/chiba/chiba.png',
        'img/Characters/chiba/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('토메상 (감식반 아저씨)',
        '불명',
        '"반장님. 피해자의 지문이 묻는 컵을 조사해봤는데요. 독은 검출되지 않았습니다."',
        '경시청 형사부 감식과의 감식관.',
        'img/Characters/tomesan/tomesan.png',
        'img/Characters/tomesan/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('미야모토 유미 (김유미)',
        '28세',
        '"공무집행방해로 벌금물고 싶어?! 좋은 말로 할 때 얼른 비키란 말이야!!"',
        '경시청 교통부 교통부 교통안전과의 경찰관. 사토형사의 절친이다.' || CHR(10) ||
        '사토 x 타카기의 연애를 어떤 때는 밀어주다가도 어떤 때는 방해하기도 한다.' || CHR(10) ||
        '현재 기사인 하네다 슈키치와 연인 관계이다. 그의 직업을 모른채로 한번 헤어진 적이 있다.',
        'img/Characters/miyamoto/miyamoto.png',
        'img/Characters/miyamoto/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('미이케 나에코(정나혜)',
        '24세',
        '"경찰을 우습게 보지 말라구요!"',
        '경시청 교통부 교통안전과의 경찰관. 같은 과의 유미와 같이 다닌다.' || CHR(10) ||
        '치바 형사와는 초등학교 동창으로 지금도 짝사랑중이다.',
        'img/Characters/miike/miike.png',
        'img/Characters/miike/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('마츠모토 키요나가 (박종태)',
        '54세',
        '"우리 경찰의 명예를 걸고 반드시 막아야 하네."',
        '경시청 수사1과 강력3계 경시이자 관리관.' || CHR(10) ||
        '메구레의 상사로, 눈가로 가로지르는 흉터가 있어 인상이 험악해 보인다.',
        'img/Characters/matsumoto/matsumoto.png',
        'img/Characters/matsumoto/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('나카모리 긴조 (임은삼)',
        '41세',
        '"드디어 나왔구나 키드. 전 대원 각자 위치로!"',
        '경시청 수사2과 지능범죄수사계 경부. 코고로와 외형이 닮았지만 실제로는 앙숙 관계.' || CHR(10) ||
        '‘괴도 키드’ 체포에 온 힘을 쏟지만, 번번이 실패한다.' || CHR(10) ||
        '그 외 사건에선 노련한 지능범 수사관으로서 유능하다.',
        'img/Characters/nakamori/nakamori.png',
        'img/Characters/nakamori/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('핫토리 헤이조 (하평무)',
        '47세 추정',
        '"이 녀석이 하고 있는건 수사가 아니라 방해에 불과합니다. 고등학생 탐정이라고 잘난척 하면서 날뛰는거죠."',
        '오사카부 경찰본부장. 헤이지의 아버지이며,' || CHR(10) ||
        '그 통찰력은 아들 헤이지도 따라가지 못할 정도로 뛰어나다.' || CHR(10) ||
        '부하들을 잘 이끌지만, 아내에게는 의외로 약한 모습을 보이기도 한다.',
        'img/Characters/heizo/heizo.png',
        'img/Characters/heizo/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('토야마 긴시로 (서원상)',
        '47세 추정',
        '"아직까지는 제 부하입니다. 손대지 말아 주시겠습니까."',
        '오사카부 경찰본부 형사부장. 카즈하의 아버지이다.' || CHR(10) ||
        '헤이조와는 소꿉친구로, 지금까지 그의 오른팔로 절대적인 신뢰를 받고 있다.' || CHR(10) ||
        '헤이조와 다르게 농담을 좋아해, 부하인 오오타키로 부터 ''토야마 아저씨''라고 불린다.',
        'img/Characters/ginshiro/ginshiro.png',
        'img/Characters/ginshiro/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('오오타키 고로 (김대용)',
        '불명',
        '"인성이냐. 그래 알겠다. 위험한 일은 아닌거지?"',
        '오사카부 수사 1과 강력계 경부. 토야마 형사부장의 부하이며, 헤이지와 친한 사이이다.' || CHR(10) ||
        '언제나 헤이지의 무모함을 걱정하면서도 부탁을 받으면 거절하지 못하고 도와준다. ',
        'img/Characters/otaki/otaki.png',
        'img/Characters/otaki/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('요코미조 산고 (천범수)',
        '35세',
        '"코난, 또 너로구나. 유탐정님께서는 같이 안오신 거니?"',
        '시즈오카현경의 경부. 원래 사이타마현경에 있었지만, 이후 시즈오카로 이동되었다.' || CHR(10) ||
        '커리어 조 출신으로 우수한 편이고, 추리력이 뛰어나다.' || CHR(10) ||
        '쌍둥이 동생 쥬고와는 다르게 코고로를 존경하며, 자신이 ''첫번째 제자''라는 자부심을 갖고 있다.',
        'img/Characters/snago/sango.png',
        'img/Characters/sango/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('요코미조 쥬고 (천범기)',
        '35세',
        '"아, 이거 미안하구만. 별 같잖은 얘기를 들으니까 머리가 근지러워져서 나도 모르게 팔이 올라갔네. "',
        '카나가와현경의 수사 1과 경부. 형과는 다르게 코고로를 ''잠꼬대 코고로'' 라면서 우습게 생각한다.' || CHR(10) ||
        '형과 매우 닮은 외모로 인해, 처음 만난 사람들이 그의 형과 착각하는 일이 자주 있다.',
        'img/Characters/jugo/jugo.png',
        'img/Characters/jugo/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('야마무라 미사오 (정영일)',
        '30세 추정',
        '"부름받고 날아왔습니다 짜라란~. 유탐정님께서 부르신다면 불속이든 물속이든 피로 도로가 침수되어도 어디든 달려갈 준비가 되어있습니다!"',
        '군마현 경찰본부 수사 1과 경부. 신이치의 어머니인 유키코의 광팬으로 그녀가 주연을 맡은 형사 드라마를 보고 형사가 되었다.' || CHR(10) ||
        '통찰력이나 추리력을 보면 어떻게 형사가 되었는지 의문일 정도. 코고로를 매우 존경한다.',
        'img/Characters/yamamura/yamamura.png',
        'img/Characters/yamamura/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('하기와라 켄지(하기완)',
        '향년 22세',
        '"뭐, 그때는 네가 원수를 갚아 줘."',
        '전 경시청 경비부 기동대 폭발물처리반 대원.' || CHR(10) ||
        '7년 전 폭탄 해체 중 순직했다. 마츠다 형사의 절친한 친구였다. ',
        'img/Characters/hagiwara/hagiwara.png',
        'img/Characters/hagiwara/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('마츠다 진페이 (송보윤)',
        '향년 26세',
        '"추신. 당신을 꽤 좋아했어."',
        '전 경시청 형사부 수사 1과 강력 3계 순사부장.' || CHR(10) ||
        '원래 기동대 폭발물 처리반에 소속되어 있다가 3년 전, 수사 1과에 배속되었다.' || CHR(10) ||
        '하지만 배속된지 불과 일주일만에 테러범이 관람차에 설치한 폭발물로부터 사람들을 지키기 위해 순직한다. ',
        'img/Characters/matsuda/matsuda.png',
        'img/Characters/matsuda/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('키사키 에리 (노애리)',
        '38세',
        '"제가 믿는지 아닌지가 아니라 재판원을 납득시킬 수 있는지 없는지입니다."',
        '코고로의 아내이자 란의 어머니. 10년 전부터 어떤 이유로 별거 중이다.' || CHR(10) ||
        '추리력과 판단력이 뛰어난 유능한 변호사로, ''법정의 여왕''이라 불린다.' || CHR(10) ||
        '카리스마 넘치는 태도로 코난을 기죽게 만들기도 하지만, 코난의 능력을 정당하게 평가해 준다.',
        'img/Characters/kisaki/kisaki.png',
        'img/Characters/kisaki/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('아카이 슈이치 (이상윤)',
        '32세',
        '"이제야 만나는군… 사랑하는 「숙적」 나으리. 아니, 「연인」이던가?"',
        'FBI 수사관이자 저격의 명수. 검은 비니와 담배 물고 있는 모습이 트레이드마크.' || CHR(10) ||
        '검은 조직에 잠입 수사했고, 코드네임은 ''라이''.' || CHR(10) ||
        '시크하고 중후한 성격으로, 현재는 ''오키야 스바루''로 위장 중이다.',
        'img/Characters/akai/akai.png',
        'img/Characters/akai/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('조디 스털링',
        '28세',
        '"Bye Bye... cool guy..."',
        'FBI 수사관. 일본의 아케이드 게임에 빠져 있으며,' || CHR(10) ||
        '20년 전 어머니와 함께 베르무트에게 아버지를 잃었다.' || CHR(10) ||
        '처음 일본에 왔을 때는 ''조디 센티밀리언''이라는 가명으로 고등학교 영어 교사로 잠입 수사했다.',
        'img/Characters/jodie/jodie.png',
        'img/Characters/jodie/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('제임스 블랙',
        '50대 중반 추정',
        '"훌륭하군. 자네가 입이 닳도록 칭찬할만 해. FBI에 스카우트 하고 싶을 정도야."',
        'FBI 지국장이자 수사관. 조디와 아카이의 상사로, 침착한 성격이라 웬만한 일엔 동요하지 않는다.' || CHR(10) ||
        '과거 유명인으로 오인받아 납치된 적이 있으나, 코난의 활약으로 구출됐다.',
        'img/Characters/james/james.png',
        'img/Characters/james/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('안드레 캐멀',
        '27세',
        '"여기서 탈출하게 되면 저한테 꼭 말씀해 주세요. 제가 운전 하나는 아주 잘하거든요."',
        'FBI 수사관. 큰 덩치와 달리 섬세한 성격을 가졌으며, 가끔 실수를 하지만 남다른 운전 실력으로 팀에 공헌한다.',
        'img/Characters/camel/camel.png',
        'img/Characters/camel/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('진',
        '불명',
        '"보고 싶었다... 셰리... 아름답지 않나? 어둠에 흩날리는 하얀 눈, 그것을 물들이는 붉은 피..."',
        '코난에게 개발중인 약을 먹인 장본인. 검은 조직의 간부급으로,' || CHR(10) ||
        '보스와 직접 연락을 주고 받는 인물이다. 포르쉐 365A를 끌고 다니며, 항상 부하인 워커와 함께 다닌다.' || CHR(10) ||
        '차갑고 냉소적인 성격으로, 조직에 해가 되는 자는 가차 없이 제거한다.',
        'img/Characters/jin/jin.png',
        'img/Characters/jin/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('워커',
        '불명',
        '"역시, 형님이십니다."',
        '검은 조직에서 잠입 수사나 실전 임무를 맡는 인물.' || CHR(10) ||
        '진의 부하로 항상 같이 다닌다. ''보드카(Vodka)''에서 이름이 유래되었으며,' || CHR(10) ||
        '페도라와 선글라스를 써서 얼굴이 거의 알려지지 않았다.',
        'img/Characters/vodka/vodka.png',
        'img/Characters/vodka/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('베르무트',
        '29세 / 50대',
        '"A secret makes a woman woman."',
        '검은 조직 보스가 특별히 총애하는 직속 부하. 변장에 능하며, 셰리를 쫓기 위해' || CHR(10) ||
        '여러 인물로 변신한 적이 있다. 코난과 하이바라의 정체를 알아챘지만,' || CHR(10) ||
        '어째서인지 이를 조직에 알리지 않는다.',
        'img/Characters/vermouth/vermouth.png',
        'img/Characters/vermouth/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('키안티',
        '불명',
        '"빨랑 지시 안 하면 흥분한 내 라이플이 무슨 짓 저지를지 몰라!"',
        '검은 조직의 실력있는 스나이퍼. 호전적이며 성급한 모습도 보인다.' || CHR(10) ||
        '과거 같은 조직의 스나이퍼인 칼바도스가 죽은 일로 인해 베르무트와 사이가 좋지 않다.',
        'img/Characters/chianti/chianti.png',
        'img/Characters/chianti/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('코른',
        '불명',
        '"칼바도스. 저 여자 좋아했다. 저 여자. 칼바도스 이용했다. 그래서 싫다"',
        '키안티와 마찬가지로 검은 조직의 스나이퍼.' || CHR(10) ||
        '과묵하고 냉정하며 묵묵히 살인을 행하는 모습도 보인다.' || CHR(10) ||
        '키안티와 마찬가지로 베르무트를 싫어한다.',
        'img/Characters/corun/corun.png',
        'img/Characters/corun/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('하네다 슈키치 (우상길)',
        '28세',
        '"뭐, 훤히 보이지. 승리의 수가."',
        '과거 7관왕도 달성한 적이 있는 프로기사. 현재는 6관왕이다.' || CHR(10) ||
        '경시청 교통부의 유미와 연인관계. 아카이 가문의 둘째로 슈이치의 동생이다.',
        'img/Characters/haneda/haneda.png',
        'img/Characters/haneda/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('핫토리 시즈카 (윤정화)',
        '42세',
        '"이봐요. 생명이란 내 거든 남의 것이든 모두 다 소중한 거라고요."',
        '핫토리 헤이조의 아내로, 헤이지의 어머니이다.' || CHR(10) ||
        '평소 일본 전통의상을 입고 다니며, 검도 유단자이다.' || CHR(10) ||
        '아들바보같은 면이 있어서, 헤이지의 성장 비디오를 찍곤 한다.',
        'img/Characters/shizuka/shizuka.png',
        'img/Characters/shizuka/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('아무로 토오루 / 후루야 레이 / 버본 (안기준 / 강준영 / 버본 )',
        '29세',
        '"저리 비켜, 이상윤!"',
        '코고로의 제자가 되어 사무소 아래에 있는 ''포와로'' 카페에서 아르바이트를 하며,' || CHR(10) ||
        '검은 조직에서는 ''버본''이라는 코드네임으로 정보 수집 중.' || CHR(10) ||
        '그러나 사실 그는 트리플 페이스로 공안 경찰인 통칭 ''제로''인 ''후루야 레이''이다.',
        'img/Characters/amuro/amuro.png',
        'img/Characters/amuro/main_img.png');

INSERT INTO characters_test_nr
(name, age, quote, description, button_image, main_image)
VALUES ('미즈나시 레나 / 혼도 히데미 / 키르 (손예나 / 문재인 / 키르 )',
        '27세',
        '"우리의 공적은 비록 빛 볼 일은 없지만 실패하면 바로 티가 나니까."',
        '인기 아나운서로 위장 중이지만, 사실 검은 조직에서 ''키르''로 활동하는 CIA 첩보원이다.' || CHR(10) ||
        '잠입 임무를 수행 중이며, 실패가 곧 노출로 이어지는 중압감 속에서 움직이고 있다.',
        'img/Characters/mizunashi/mizunashi.png',
        'img/Characters/mizunashi/main_img.png');

