create table board_table_test(
    b_no varchar2(20 char) unique,
    b_id varchar2(20 char) primary key,
    b_name varchar2(20 char) not null,
    b_begin varchar2(40 char) not null,
    b_title varchar2(200 char) not null,
    b_text varchar2(4000 char) not null,
    b_date date not null);




create sequence board_table_test_seq;

insert into board_table_test values (board_table_test_seq.nextval,'sh04070', 'kim', '가입인사','안녕하세요' ,'코난이 참 좋아요', sysdate);

select * from board_table_test;

 drop table board_table_test;
;

CREATE TABLE board_free_comment (
                                c_no INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  -- 댓글 고유 번호
                                b_no VARCHAR2(10) NOT NULL,                             -- 댓글이 속한 게시글 번호
                                c_writer VARCHAR2(100) NOT NULL,                        -- 댓글 작성자
                                c_content CLOB NOT NULL,                                -- 댓글 내용 (TEXT 대신 CLOB 사용)
                                c_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,             -- 댓글 작성 시간
                                FOREIGN KEY (b_no) REFERENCES board_table_test(b_no) ON DELETE CASCADE -- 게시글 테이블과 외래키 연결
);

create sequence board_free_comment_seq;

insert into board_free_comment (b_no, c_writer, c_content, c_date)values (130, '진현', '좋은글입니다.', systimestamp);
select * from board_free_comment;

drop table board_free_comment;